<?php

/**
 * @file Main file for the vertical tabs module - provides vertical tabs on the
 * node form.
 */

/**
 * Implementation of hook_theme().
 */
function vertical_tabs_theme() {
  return array(
    'vertical_tabs' => array(
      'arguments' => array('form_element' => NULL),
    ),
    'vertical_tabs_js_css' => array(
      'arguments' => array('js' => NULL, 'css' => NULL, 'settings' => NULL, 'form_id' => NULL),
    ),
  );
}

/**
 * Implementation of hook_form_alter.
 */
function vertical_tabs_form_alter(&$form, $form_state, $form_id) {
  $fieldsets = array();
  $node_form = FALSE;
  // Check to see which form we are in. Since the node form's form id is not
  // just node_form, we can't implement a function for all node forms, so we are
  // stuck implementing the global form_alter and checking if there is the
  // string node_form in the form id.
  if (strpos($form_id, 'node_form')) {
    // The $fieldsets array is a list of all supported fieldsets in core
    // for the node form, and their JavaScript summary creators.
    $fieldsets = array(
      'book' => 'book',
      'revision_information' => 'revision',
      'author' => 'authoring',
      'options' => 'publishingOptions',
      'menu' => 'menu',
      'comment_settings' => 'comment',
      'path' => 'path',
      'attachments' => 'attachments',
    );
    $node_form = TRUE;
  }
  if ($node_form) {
    // The javascript to add to the page.
    $settings = array();
    // Iterate through the form, finding fieldsets.
    foreach (element_children($form) as $key) {
      // We need to make sure that the element we have is a fieldset
      // and the user has access to this field.
      if (isset($form[$key]['#type']) && $form[$key]['#type'] == 'fieldset' &&
        (!isset($form[$key]['#access']) || $form[$key]['#access'] != FALSE)) {
        // Add the JavaScript.
        $settings[$key] = array('name' => $form[$key]['#title']);
        // If there's a summary callback, then add it.
        if (isset($form[$key]['#summary_callback']) || isset($fieldsets[$key])) {
          $settings[$key]['callback'] = (isset($form[$key]['#summary_callback']) ? $form[$key]['#summary_callback'] : $fieldsets[$key]);
          $settings[$key]['args'] = (isset($form[$key]['#summary_arguments']) ? $form[$key]['#summary_arguments'] : array());
        }
        // Add a class to identify the fieldset.
        if (isset($form[$key]['#attributes']['class']) && !empty($form[$key]['#attributes']['class'])) {
          $form[$key]['#attributes']['class'] .= ' vertical-tabs-fieldset vertical-tabs-'. $key;
        }
        else {
          $form[$key]['#attributes']['class'] = 'vertical-tabs-fieldset vertical-tabs-'. $key;
        }
      }
    }

    // The JavaScript and CSS specific for this form.
    $js = array(drupal_get_path('module', 'vertical_tabs') .'/vertical_tabs.node_form.js');
    $css = array();

    $form['vertical_tabs'] = array(
      '#vertical_tabs_settings' => $settings,
      '#vertical_tabs_js' => $js,
      '#vertical_tabs_css' => $css,
      '#form_id' => $form_id,
      '#type' => 'markup',
      '#value' => '',
      '#weight' => 100,
      '#theme' => 'vertical_tabs',
    );
  }
}

/**
 * After build function to add vertical tabs JS and CSS to the form.
 */
function theme_vertical_tabs(&$form_element) {
  theme('vertical_tabs_js_css', $form_element['#vertical_tabs_js'], $form_element['#vertical_tabs_css'], $form_element['#vertical_tabs_settings'], $form_element['#form_id']);
  return '<div class="vertical-tabs">&nbsp;</div>';
}

/**
 * 
 */
function theme_vertical_tabs_js_css($js, $css, $settings, $form_id) {
  static $js_added = array();
  if (!isset($js_added[$form_id])) {
    drupal_add_js(array('verticalTabs' => $settings), 'setting');
    drupal_add_js(drupal_get_path('module', 'vertical_tabs') .'/vertical_tabs.js', 'theme');
    drupal_add_css(drupal_get_path('module', 'vertical_tabs') .'/vertical_tabs.css', 'theme');
    foreach ($js as $path) {
      drupal_add_js($path, 'theme');
    }
    foreach ($css as $path) {
      drupal_add_css($path, 'theme');
    }
    $js_added[$form_id] = TRUE;
  }
}